name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create Kaggle config
        run: | 
          mkdir $HOME/.kaggle
          echo '{"username":"${{ secrets.KAGGLE_USERNAME }}","key":"${{ secrets.KAGGLE_KEY }}"}' > $HOME/.kaggle/kaggle.json
          chmod 600 $HOME/.kaggle/kaggle.json

      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings -q

      - name: Code quality
        run: |
          black --check .
          ruff check .

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: your-dockerhub-username/your-image-name:latest

      - name: Deploy to Render
        run: |
          curl -X POST https://api.render.com/deploy/some-endpoint \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          -H "Content-Type: application/json" \
          -d '{"service_id": "your-service-id"}'
