name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job pour installer les dépendances et exécuter les tests
  setup-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create Kaggle config
        run: | 
          mkdir $HOME/.kaggle
          echo '{"username":"${{ secrets.KAGGLE_USERNAME }}","key":"${{ secrets.KAGGLE_KEY }}"}' > $HOME/.kaggle/kaggle.json
          chmod 600 $HOME/.kaggle/kaggle.json

      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings -q

      - name: Code quality
        run: |
          black --check .
          ruff check .

  # Job pour construire et pousser l'image Docker
  build-and-push:
    runs-on: ubuntu-latest
    needs: setup-and-test
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./src/API
          push: true
          tags: fatou1801/home-credit-risk:latest

  # Job pour déployer l'application sur Render
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Deploy to Render
        uses: JorgeLNJunior/render-deploy@v1.4.4
        with:
          service_id: "srv-cqpqd5jqf0us73ao2uf0"
          api_key: "rnd_yrhzmT2gIXkhtNx9Q9qzj1ts5orn"
